connector:
  - name: vm-source-1
    class: Victoriametrics
    pipeline: 
      - reader
      - writer
    params:
      datasource_url: http://localhost1:8427/
      multi_tenant: true
      user_query: vmselect
      pwd_query: asdfasdfasdf
      user_insert: vminsert
      pwd_insert: fdsafdsafdsa
  - name: vm-source-2
    class: Victoriametrics
    pipeline:
      - reader
      - writer
    params:
      datasource_url: http://localhost2:8427/
      multi_tenant: true
      user_query: vmselect
      pwd_query: asdfasdfasdf
      user_insert: vminsert
      pwd_insert: fdsafdsafdsa

model:
  - name: prophet
    class: ProphetModel

scheduler:
  - name: periodical
    class: Periodical
    params:
      max_tasks: -1