connector:
  - name: vm-source
    class: Victoriametrics
    pipeline: 
      - reader
      - writer
    params:
      datasource_url: http://localhost:8427/
      multi_tenant: true
      user_query: vmselect
      pwd_query: pwd
      user_insert: vminsert
      pwd_insert: pwd
  # - name: mq-pulsar
  #   class: Pulsar
  #   pipeline: writer
  #   params:
  #     datasource_url: pulsar://192.168.163.17:6650
  #     jwt_token: eyJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJ1c2VyIn0.QbSh6qUG_yQN7vNcRkk4_8C2nXw5ions_G29qmZXW1BXifaamSowCNHTt1pPgh1RoFlu7xzuZ2K0NCfi9Q7a1-hybMWokr-Z06DlzVx48HS3qjZ7hwNv1QOU5EkfVNekqI-zRj6ROioMIoEGliwrOM8M-Eu-EClKYt1zrRFwnETkNZml_DU1O5GRPF1pEq_BZcpoX-NbFKXPf8Doh8ko6Lw2Z8qsr40H4McGBzPw4Q-b56Rr4_OEgas7U_UNWCLvsiHuDBpW6Jbmjl6iNckG7WeiOyLL8xi2KNVyQSjYMz8G0ko1qraBH5NQfepiqnFTOfek4nTL4eZ6WLXiThC19g
  #     target_topic: persistent://dev/alerts/tp_anomalyd_result

model:
  - name: prophet
    class: ProphetModel

scheduler:
  - name: periodical
    class: Periodical
